Repository PantherHacks/pantherhacks.dev, pull requests merged in 2025-03, with the labels that each got.

#12 [added] Application Link on "Apply" Navigation Button
  components/navbar.tsx
Labels: enhancement

#20 [added] Added Drop Shadow to the Navbar
  components/navbar.tsx
Labels: enhancement

#21 [fix] Heading image is no longer blurry on mobile
  app/(main)/_components/mobileheading.tsx
Labels: enhancement

#32 [added] Social image preview
  app/layout.tsx
  public/social-images/opengraph-image.png
Labels: enhancement

#33 [added + fixed] More website details and fixes to accessibility
  app/(main)/_components/faqs-section.tsx
  app/(main)/_components/heading.tsx
  app/(main)/_components/main-content.tsx
  app/(main)/_components/mobileheading.tsx
  app/(main)/_components/track.tsx
  app/(main)/_components/tracks-section.tsx
  components/footer/footer.tsx
  components/navbar.tsx
  components/ui/NavLink.tsx
  public/images/main-background/main-header-transition-test.svg
  public/images/main-background/main-header-transition.svg
  public/images/oranges/orange-branch-1.svg
  public/images/oranges/orange-branch-2.svg
  public/images/oranges/orange-branch-mobile-divider.svg
  public/images/tracks/ai-mobile.svg
  public/images/tracks/ai.svg
  public/images/tracks/cybersecurity-mobile.svg
  public/images/tracks/cybersecurity.svg
  public/images/tracks/healthcare-mobile.svg
  public/images/tracks/healthcare.svg
  public/images/tracks/sustainability-mobile.svg
  public/images/tracks/sustainability.svg
Labels: enhancement

#34 [added] FAQ starter questions
  app/(main)/_components/faqs-section.tsx
Labels: enhancement

#54 [fix] Header related images no longer lazy load
  app/(main)/_components/heading.tsx
  app/(main)/_components/main-content.tsx
  app/(main)/_components/mobileheading.tsx
Labels: type: fix, status: awaiting review

#58 [fix] Horizontal scroll on transition svg and main page
  app/(main)/_components/main-content.tsx
  app/layout.tsx
Labels: type: fix, status: awaiting review

#59 [release] v0.0.8
  .github/ISSUE_TEMPLATE/01--issue-with-website.yml
  .github/ISSUE_TEMPLATE/02--feature-request.yml
  app/(main)/_components/heading.tsx
  app/(main)/_components/main-content.tsx
  app/(main)/_components/mobileheading.tsx
  app/(main)/_components/track.tsx
  app/(main)/_components/tracks-section.tsx
  app/layout.tsx
  package-lock.json
  package.json
Labels: type: release

#67 [added] /apply redirects you to application page
  app/(application)/apply/page.tsx
Labels: type: addition, status: awaiting review

#64 [added] Improved readme + contributing code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: type: addition, status: awaiting review

#62 [added] Team section
  app/(main)/_components/_team/team-member.css
  app/(main)/_components/_team/team-member.tsx
  app/(main)/_components/_team/team-section.tsx
  app/(main)/_components/main-content.tsx
  components/navbar.tsx
  public/images/team-members/daniel-tsivkovski.png
  public/images/team-members/dylan-ravel.png
  public/images/team-members/kalin-richardson.png
  public/images/team-members/nataniel-farzan.png
  public/images/team-members/owen-agbayani.png
  public/images/team-members/sam-fago.png
  public/images/team-members/temp-pic.jpg
Labels: type: addition, status: awaiting review

#68 [fix] Uniform line endings
  .prettierrc.json
  CODE_OF_CONDUCT.md
Labels: type: fix, status: awaiting review

#60 [addition] Prizes Section
  .idea/codeStyles/Project.xml
  app/(main)/_components/_prizes/prize.css
  app/(main)/_components/_prizes/prize.tsx
  app/(main)/_components/_prizes/prizes-section.tsx
  app/(main)/_components/main-content.tsx
  components/navbar.tsx
  public/images/panther/panther.png
  public/images/panther/panther.svg
  public/images/prizes/crucial-ssd.png
  public/images/prizes/keychron-k4.png
  public/images/prizes/piranha-plant.png
  public/images/prizes/raspberry-pi.png
  public/images/prizes/retro-console.png
Labels: type: addition

#69 [fix] Improved orange spacing and margins
  app/(main)/_components/_prizes/prizes-section.tsx
  app/(main)/_components/_team/team-section.tsx
  app/(main)/_components/about-section.tsx
  app/(main)/_components/faqs-section.tsx
  app/(main)/_components/tracks-section.tsx
  components/navbar.tsx
Labels: type: fix, status: awaiting review

#71 [fix] No more blur on team member and prize photos
  app/(main)/_components/_prizes/prize.tsx
  app/(main)/_components/_team/team-member.tsx
Labels: type: fix, status: awaiting review

#70 [release] v0.0.9
  .idea/codeStyles/Project.xml
  .prettierrc.json
  CODE_OF_CONDUCT.md
  README.md
  app/(application)/apply/page.tsx
  app/(main)/_components/_prizes/prize.css
  app/(main)/_components/_prizes/prize.tsx
  app/(main)/_components/_prizes/prizes-section.tsx
  app/(main)/_components/_team/team-member.css
  app/(main)/_components/_team/team-member.tsx
  app/(main)/_components/_team/team-section.tsx
  app/(main)/_components/about-section.tsx
  app/(main)/_components/faqs-section.tsx
  app/(main)/_components/main-content.tsx
  app/(main)/_components/tracks-section.tsx
  components/navbar.tsx
  package-lock.json
  package.json
  public/images/panther/panther.png
  public/images/panther/panther.svg
  public/images/prizes/crucial-ssd.png
  public/images/prizes/keychron-k4.png
  public/images/prizes/piranha-plant.png
  public/images/prizes/raspberry-pi.png
  public/images/prizes/retro-console.png
  public/images/team-members/daniel-tsivkovski.png
  public/images/team-members/dylan-ravel.png
  public/images/team-members/kalin-richardson.png
  public/images/team-members/nataniel-farzan.png
  public/images/team-members/owen-agbayani.png
  public/images/team-members/sam-fago.png
  public/images/team-members/temp-pic.jpg
Labels: status: awaiting review, type: release

#73 [added] Additional team member
  app/(main)/_components/_team/team-section.tsx
  public/images/team-members/joel-escobar.png
Labels: type: addition, status: awaiting review

#72 [fix] Changed the wording of the prize section
  app/(main)/_components/_prizes/prizes-section.tsx
Labels: type: fix, status: awaiting review

#75 [addition] Footer arch gradient
  app/(main)/_components/_team/team-section.tsx
  components/footer/footer.tsx
  package-lock.json
  public/images/arch/Arch.svg
Labels: status: awaiting review

#76 [fix] Team member drop shadow dark instead of light
  app/(main)/_components/_team/team-member.css
Labels: type: fix, status: awaiting review

#78 [fix] slightly decreased drop shadow for team member names
  app/(main)/_components/_team/team-member.css
Labels: status: awaiting review

#79 [refactor] Organized tracks and headings into directories, Accesibility for Readme
  README.md
  app/(main)/_components/_headings/heading.tsx
  app/(main)/_components/_headings/mobileheading.css
  app/(main)/_components/_headings/mobileheading.tsx
  app/(main)/_components/_headings/parallax.css
  app/(main)/_components/_team/team-member.css
  app/(main)/_components/_tracks/track.css
  app/(main)/_components/_tracks/track.tsx
  app/(main)/_components/_tracks/tracks-section.tsx
  app/(main)/_components/main-content.tsx
Labels: status: awaiting review

#82 [fix] Nav link + navbar size shifting
  components/navbar.tsx
  components/ui/NavLink.tsx
Labels: type: fix, status: awaiting review

#83 [addition] Navbar Title
  components/navbar.tsx
Labels: status: awaiting review

#81 [release] v1.0.0
  README.md
  app/(main)/_components/_headings/heading.tsx
  app/(main)/_components/_headings/mobileheading.css
  app/(main)/_components/_headings/mobileheading.tsx
  app/(main)/_components/_headings/parallax.css
  app/(main)/_components/_prizes/prizes-section.tsx
  app/(main)/_components/_team/team-member.css
  app/(main)/_components/_team/team-member.tsx
  app/(main)/_components/_team/team-section.tsx
  app/(main)/_components/_tracks/track.css
  app/(main)/_components/_tracks/track.tsx
  app/(main)/_components/_tracks/tracks-section.tsx
  app/(main)/_components/main-content.tsx
  app/not-found.tsx
  components/footer/footer.tsx
  components/navbar.tsx
  package-lock.json
  package.json
  public/images/arch/Arch.svg
  public/images/panther/404-panther.png
  public/images/panther/panther.png
  public/images/panther/panther.svg
  public/images/team-members/joel-escobar.png
Labels: status: awaiting review, type: release

#87 [fix] Max width sizing for about section text
  app/(main)/_components/about-section.tsx
Labels: status: awaiting review

#91 [release] v1.1.0
  app/(main)/_components/_team/team-section.tsx
  app/(main)/_components/about-section.tsx
  app/(main)/_components/countdown.tsx
  lib/countdown.ts
  lib/dates.ts
  package-lock.json
  package.json
  public/images/team-members/daniel-min.png
Labels: status: awaiting review, type: release

#92 [fix] Asymmetrical padding after countdown
  app/(main)/_components/countdown.tsx
Labels: type: fix, status: awaiting review

#93 [release] v1.1.1
  app/(main)/_components/countdown.tsx
  package-lock.json
  package.json
Labels: status: awaiting review, type: release
