Repository PantherHacks/pantherhacks.dev, pull requests merged in 2025-04, with the labels that each got.

#97 [release] v1.1.3
  package-lock.json
  package.json
Labels: status: awaiting review, type: release

#98 [release] v1.1.4
  app/(main)/_components/countdown.tsx
  package-lock.json
  package.json
Labels: status: awaiting review, type: release

#101 [refactor] Rules Page now sits in the `(event)` folder
  app/(event)/rules/page.tsx
  app/globals.css
Labels: status: awaiting review, type: refactor

#103 [fix] Margins for rules page bullet points
  app/(event)/rules/page.tsx
Labels: status: awaiting review

#102 [release] v1.2.0
  app/(event)/rules/page.tsx
  app/globals.css
  lib/dates.ts
  lib/links.ts
  package-lock.json
  package.json
Labels: status: awaiting review, type: release

#104 [added] Live event page (WIP)
  app/(event)/live/_components/event-card.tsx
  app/(event)/live/_components/live-heading.tsx
  app/(event)/live/_components/live.css
  app/(event)/live/_components/schedule-helpers.ts
  app/(event)/live/_components/schedule.tsx
  app/(event)/live/page.tsx
  app/(main)/_components/about-section.tsx
  components/countdown.tsx
  components/footer/footer.tsx
  components/ui/badge.tsx
  components/ui/separator.tsx
  lib/links.ts
  package-lock.json
  package.json
  public/images/oranges/orange-loader.svg
Labels: type: addition, status: awaiting review

#108 [added] Add to calendar button on events
  app/(event)/live/_components/event-card.tsx
  app/(event)/live/_components/schedule-helpers.ts
Labels: type: addition, status: awaiting review

#109 [added] Live Schedule filters by event type
  app/(event)/live/_components/schedule-filters.tsx
  app/(event)/live/_components/schedule.tsx
  package-lock.json
Labels: status: awaiting review

#111 [added] /schedule and /countdown
  app/(event)/countdown/page.tsx
  app/(event)/schedule/page.tsx
  components/countdown.tsx
  public/images/countdown/countdown-mountain.svg
  public/images/countdown/mountain-1.svg
  public/images/countdown/mountain-2.svg
Labels: type: addition, status: awaiting review

#114 [added] Important Links section on `/live` page
  app/(event)/countdown/page.tsx
  app/(event)/live/_components/important-link.tsx
  app/(event)/live/_components/important-links.tsx
  app/(event)/live/_components/schedule.tsx
  app/(event)/live/page.tsx
  lib/links.ts
Labels: type: addition, status: awaiting review

#116 [added] Replaced `APPLY` nav button with `LIVE` nav button
  app/(application)/apply/page.tsx
  app/(event)/live/page.tsx
  app/(event)/rules/page.tsx
  app/(event)/schedule/page.tsx
  app/(main)/page.tsx
  app/not-found.tsx
  components/navbar/navbar.css
  components/navbar/navbar.tsx
  package-lock.json
Labels: type: addition, status: awaiting review

#118 [fix] Countdown, Navbar Link, and Important Link Fixes
  app/(event)/live/_components/important-link.tsx
  components/countdown.tsx
  components/navbar/navbar.tsx
  package-lock.json
Labels: status: awaiting review

#117 [addition] Previous date filter
  app/(event)/live/_components/event-card.tsx
  app/(event)/live/_components/live.css
  app/(event)/live/_components/schedule.tsx
  components/ui/switch.tsx
  package-lock.json
  package.json
Labels: status: awaiting review

#119 [fix] Cursor will hide on countdown page automatically
  app/(event)/countdown/page.tsx
Labels: status: awaiting review

#121 [added] Fullscreen button for countdown page
  app/(event)/countdown/page.tsx
Labels: type: addition, status: awaiting review

#122 [release] v1.3.1
  app/(event)/countdown/page.tsx
  package-lock.json
  package.json
Labels: status: awaiting review, type: release

#123 [added + fixed] loading skeleton on countdown and wording change
  components/countdown.tsx
  components/ui/skeleton.tsx
  lib/countdown.ts
  package-lock.json
Labels: type: addition, status: awaiting review

#124 [release] v1.3.2
  components/countdown.tsx
  components/ui/skeleton.tsx
  lib/countdown.ts
  package-lock.json
  package.json
Labels: status: awaiting review, type: release

#126 [release] v1.3.3
  app/(event)/live/_components/schedule.tsx
  package-lock.json
  package.json
Labels: status: awaiting review, type: release

#127 [added] Show a message when there are no upcoming events
  app/(event)/live/_components/schedule.tsx
Labels: type: addition, status: awaiting review

#128 [added] Confetti on hackathon completion
  app/(event)/countdown/page.tsx
  components/countdown.tsx
  lib/countdown.ts
  package-lock.json
  package.json
Labels: type: addition, status: awaiting review

#129 [release] v1.3.4
  app/(event)/countdown/page.tsx
  app/(event)/live/_components/schedule.tsx
  components/countdown.tsx
  lib/countdown.ts
  package-lock.json
  package.json
Labels: status: awaiting review, type: release
